spring.application.name=CommuteMate

server.port=${PORT:8080}


spring.datasource.url=jdbc:h2:file:./data/commutemate
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true